# Generated by Django 3.1.5 on 2021-01-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
                ('courseNumber', models.IntegerField(default='', max_length=60)),
                ('instructorName', models.CharField(default='', max_length=60)),
                ('duration', models.FloatField(default='', max_length=60)),
            ],
        ),
    ]
